# This workflow pushes a package to nuget.org

name: Push Package To nuget.org
on:
  #push:
   # branches:
    #  - main # Default release branch
  workflow_dispatch:

env:
  # Filepath of the project to be packaged, relative to root of repository
  PROJECT: mitoSoft.GitHub.Versioning/mitoSoft.GitHub.Versioning.csproj
  
jobs:
  publish:
    name: build, pack & publish 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ${{env.PROJECT}}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # optional
          INCLUDE_SYMBOLS: false # optional, default is true